services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-etape}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-etape}
      POSTGRES_DB: ${POSTGRES_DB:-etape}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
